# Generated by Django 4.2.20 on 2026-10-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_national_id_user_photo_data_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Super Super Admin'), ('super_admin', 'Super Administrateur'), ('cooperative', 'Coopérative'), ('agent', 'Agent Mappeur')], default='agent', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organisation cliente')),
                ('max_cooperatives', models.PositiveIntegerField(blank=True, null=True, verbose_name='Coopératives max.')),
                ('max_agents_per_coop', models.PositiveIntegerField(blank=True, null=True, verbose_name='Agents max. par coopérative')),
                ('modules', models.JSONField(blank=True, default=list, verbose_name='Modules activés')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name="Fin d'abonnement")),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licence super admin',
                'verbose_name_plural': 'Licences super admin',
            },
        ),
    ]
