# Generated by Django 4.2.20 on 2026-10-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0006_agent_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0003_assign_existing_cooperatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Numéro de lot')),
                ('campaign', models.CharField(max_length=20, verbose_name='Campagne')),
                ('product', models.CharField(choices=[('cacao', 'Cacao (fèves)'), ('cafe', 'Café (vert)'), ('autre', 'Autre')], default='cacao', max_length=10)),
                ('lot_date', models.DateField(verbose_name='Date de constitution')),
                ('bags', models.PositiveIntegerField(default=0, verbose_name='Nombre de sacs')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Poids brut (kg)')),
                ('quality', models.CharField(blank=True, max_length=60, verbose_name='Qualité / grade')),
                ('warehouse', models.CharField(blank=True, max_length=120, verbose_name='Magasin')),
                ('buyer', models.CharField(blank=True, max_length=200, verbose_name='Acheteur / exportateur')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('transport', models.CharField(blank=True, max_length=120, verbose_name='Transport (camion, immatriculation)')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('expedie', 'Expédié')], default='brouillon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot',
                'ordering': ['-lot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bags', models.PositiveIntegerField(default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('receipt', models.CharField(blank=True, max_length=60, verbose_name='N° de bon / reçu')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lots.lot')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_lines', to='producers.producer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
