# Generated by Django 4.2.20 on 2026-09-28 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrySheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la feuille')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('data', models.JSONField(blank=True, default=list, verbose_name='Cellules')),
                ('col_widths', models.JSONField(blank=True, default=list, verbose_name='Largeur des colonnes (px)')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name="Fichier Excel d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_sheets', to='cooperatives.cooperative')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feuille du registre',
                'verbose_name_plural': 'Feuilles du registre',
                'ordering': ['cooperative', 'position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrysheet',
            constraint=models.UniqueConstraint(fields=('cooperative', 'name'), name='registry_sheet_unique_name'),
        ),
    ]
