# Generated by Django 4.2.20 on 2026-10-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrysheet',
            name='formats',
            field=models.JSONField(blank=True, default=dict, verbose_name='Mise en forme'),
        ),
        migrations.AddField(
            model_name='registrysheet',
            name='tables',
            field=models.JSONField(blank=True, default=list, verbose_name='Tableaux'),
        ),
    ]
