# Generated by Django 4.2.30 on 2026-06-26 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(max_length=80, unique=True, verbose_name='FIELD ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom de la parcelle')),
                ('geometry', models.JSONField(verbose_name='Géométrie GeoJSON')),
                ('area_hectares', models.FloatField(default=0.0, verbose_name='Superficie (ha)')),
                ('perimeter_meters', models.FloatField(default=0.0, verbose_name='Périmètre (m)')),
                ('vertex_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de sommets')),
                ('culture', models.CharField(default='Cacao', max_length=100, verbose_name='Culture')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('eudr_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score EUDR (%)')),
                ('eudr_status', models.CharField(choices=[('compliant', 'Conforme'), ('non_compliant', 'Non conforme'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('validation_result', models.JSONField(blank=True, null=True, verbose_name='Résultat validation EUDR')),
                ('mapping_started_at', models.DateTimeField(blank=True, null=True)),
                ('mapping_ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='producers.agent')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='cooperatives.cooperative')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='producers.producer')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
