# Generated by Django 4.2.20 on 2026-09-28 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyParcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('geometry', models.JSONField(verbose_name='Géométrie GeoJSON (WGS84)')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='Attributs')),
                ('area_hectares', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Fichier source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_parcels', to='cooperatives.cooperative')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ancien polygone',
                'verbose_name_plural': 'Anciens polygones',
                'ordering': ['source_file', 'name'],
                'indexes': [models.Index(fields=['cooperative', 'source_file'], name='parcels_leg_coopera_33bcc1_idx')],
            },
        ),
    ]
