# Generated by Django 4.2.20 on 2026-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_legacyparcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Enclave', 'Enclave'), ('Parc/reserve', 'Parc / réserve'), ('Foret classee', 'Forêt classée'), ('Agro-foret classee', 'Agro-forêt classée')], db_index=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField(verbose_name='Géométrie GeoJSON (WGS84)')),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone foncière (RDUE)',
                'verbose_name_plural': 'Zones foncières (RDUE)',
                'ordering': ['category', 'name'],
            },
        ),
    ]
