# Generated by Django 4.2.20 on 2026-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_landzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Identifiant hors ligne'),
        ),
    ]
