# Generated by Django 4.2.20 on 2026-10-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0007_producer_match_key_alter_producer_field_id_base_and_more'),
        ('parcels', '0004_parcel_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyparcel',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code (attributs)'),
        ),
        migrations.AddField(
            model_name='legacyparcel',
            name='match_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=110),
        ),
        migrations.AddField(
            model_name='legacyparcel',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_parcels', to='producers.producer'),
        ),
    ]
