# Generated by Django 4.2.30 on 2026-06-26 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('rccm', models.CharField(max_length=100, unique=True, verbose_name='RCCM')),
                ('agrement', models.CharField(blank=True, max_length=100, verbose_name='Agrément')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cooperative_logos/')),
                ('pca', models.CharField(blank=True, max_length=255, verbose_name='PCA')),
                ('adg', models.CharField(blank=True, max_length=255, verbose_name='ADG')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Directeur')),
                ('sig_manager', models.CharField(blank=True, max_length=255, verbose_name='Responsable SIG')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coopérative',
                'verbose_name_plural': 'Coopératives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='cooperative_documents/')),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cooperatives.cooperative')),
            ],
        ),
    ]
