# Generated by Django 4.2.20 on 2026-10-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='managed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cooperatives', to=settings.AUTH_USER_MODEL, verbose_name='Super admin gestionnaire'),
        ),
    ]
