# Generated by Django 4.2.20 on 2026-10-08 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=200)),
                ('profile', models.CharField(choices=[('cooperative', 'Coopérative'), ('exportateur', 'Exportateur'), ('certification', 'Organisme / certification'), ('autre', 'Autre')], default='cooperative', max_length=20)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('producers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre approximatif de producteurs')),
                ('plan', models.CharField(blank=True, max_length=30, verbose_name='Formule envisagée')),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('demo', 'Démo faite'), ('client', 'Devenue cliente'), ('sans_suite', 'Sans suite')], default='nouvelle', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de démonstration',
                'ordering': ['-created_at'],
            },
        ),
    ]
