# Generated by Django 4.2.30 on 2026-06-26 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code agent')),
                ('zone', models.CharField(blank=True, max_length=255, verbose_name='Zone de travail')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='cooperatives.cooperative')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Mappeur',
                'verbose_name_plural': 'Agents Mappeurs',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id_base', models.CharField(max_length=50, unique=True, verbose_name='FIELD ID Base')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='CNI')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de naissance')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='producers.agent')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
