# Generated by Django 4.2.20 on 2026-09-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_gmr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de naissance (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='field_id_base',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifiant interne unique'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1, verbose_name='Genre (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° identification national'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='region',
            field=models.CharField(max_length=100, verbose_name="Région d'inspection interne"),
        ),
        migrations.AlterField(
            model_name='producer',
            name='village',
            field=models.CharField(max_length=100, verbose_name='Village / Ville'),
        ),
    ]
