# Generated by Django 4.2.20 on 2026-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_producer_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données importées (Excel)'),
        ),
    ]
