# Generated by Django 4.2.20 on 2026-09-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_producer_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom (opérateur)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section'),
        ),
    ]
