# Generated by Django 4.2.20 on 2026-10-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_producer_optional_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='sections',
            field=models.JSONField(blank=True, default=list, verbose_name='Sections attribuées'),
        ),
    ]
