# Generated by Django 4.2.20 on 2026-10-08 13:11

from django.db import migrations, models


def fill_match_key(apps, schema_editor):
    # code normalisé des producteurs existants (croisement registre ↔ polygones)
    from apps.producers.matching import normalize_code
    Producer = apps.get_model('producers', 'Producer')
    batch = []
    for p in Producer.objects.only('id', 'field_id_base').iterator(chunk_size=2000):
        p.match_key = normalize_code(p.field_id_base) or ''
        batch.append(p)
        if len(batch) >= 1000:
            Producer.objects.bulk_update(batch, ['match_key'])
            batch = []
    if batch:
        Producer.objects.bulk_update(batch, ['match_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0006_agent_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='match_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='producer',
            name='field_id_base',
            field=models.CharField(max_length=50, verbose_name='Code producteur (registre)'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(fields=('cooperative', 'field_id_base'), name='producer_code_unique_per_coop'),
        ),
        migrations.RunPython(fill_match_key, migrations.RunPython.noop),
    ]
