# Generated by Django 4.2.20 on 2026-10-04 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperatives', '0003_assign_existing_cooperatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deforestation', 'Analyse déforestation'), ('validator', 'Polygon Validator (chevauchements)'), ('selfintersection', 'Self-intersection (nettoyage)'), ('gmr', 'Polygon & GMR (registre × polygones)'), ('import_registry', 'Import du registre'), ('import_polygons', 'Import de polygones')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(blank=True, default=list)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('content', models.BinaryField()),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de traitement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cooperative', 'kind', '-created_at'], name='reports_ana_coopera_c9df0f_idx')],
            },
        ),
    ]
